// C++ includes used for precompiling -*- C++ -*-
// Copyright (C) 2024 MC_BE.
// Building time 2024/7/22
/** @file chinese.h
 *  This is an implementation file for a precompiled header.
 */
#include<bits/stdc++.h>
using namespace std;
#if __cplusplus >= 201703L
#define 引用 using
#define 命名空间 namespace
#define 标准 std
#define 宏定义 define
#define 包含 include
#define 整型 int
#define 获取字符 getchar
#define 文件输入输出 freopen
#define 输出字符串  puts
#define 输出字符 putchar
#define 双精度浮点型 double
#define 布尔型 bool
#define ； ;
#define ： :
#define （  (
#define   ） )
#define  ｛  {
#define   ｝  }
#define 无返回值型 void
#define 无符号型 unsigned
#define 短 short
#define 长 long
#define 六十四位整型 long long
#define 可变的 mutable
#define 不变的 const
#define 有符号型 signed
#define 单精度浮点型 float
#define 主函数 main
#define 返回 return
#define 牢大 24
#define 标准输入流 cin
#define 标准输出流 cout
#define 左移 <<
#define 右移 >>
#define 输出流 <<
#define 输入流 >>
#define 向量 vector
#define 集合 set
#define 链表 list
#define 映射 map  
#define 队列 deque
#define 顺序查找 find
#define 排序 sort
#define 翻转 reverse
#define 稳定排序 stable_sort
#define 查找大于等于 lower_bound
#define 查找大于 upper_bound
#define 条件循环 while
#define 变量循环 for
#define 插入 insert
#define 删除 erase
#define 判断 if
#define 开始 begin
#define 结束 end
#define 字符串 string
#define 字符数组 char
#define  ￥  $
#define  · `
#define 选择 switch 
#define 选择块 case
#define 否则 else
#define 跳过 continue
#define 跳出 break
#define 异或 xor
#define 整型最大值 INT_MAX
#define 整型最小值 INT_MIN
#define 负一  EOF
#define 长整型最大值 LONG_MAX
#define 长整型最小值 LONG_MIN
#define 大小  sizeof
#define 长度  size
#define 整型类 %d
#define 长整型类 %ld
#define 六十四位整型类 %lld
#define 字符型 %s
#define 单浮点型 %f
#define 双浮点型 %lf
#define 长浮点型 %Lf
#define 扫描 scanf
#define 打印 printf
#define 地址值 &
#define 结构体 struct 
#define 联合体 union 
#define 类 class
#define 成员 public
#define 真 true
#define 假 false
#define 最大 max
#define 最小 min
#define 指针 *
#define 迭代器 iterator
#define 默认 default
#define 如果 if
#define 结束如果 endif
#define 结束宏  undef
#define 否则如果 elif
#define 否者 else
#define c++版本  __cplusplus
#define C++版本  __cplusplus
#endif
